command_timeout = 3000
add_newline = true
continuation_prompt = "▷ "

[aws]
force_display=true
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold yellow'
symbol = 'aws '
expiration_symbol = 'X'

[aws.region_aliases]
ap-northeast-1 = '東京'

[directory]
truncation_length = 10

[container]
disabled = true

[character]
error_symbol = '[✗](bold red)'

[git_status]
stashed = '📦 '

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'bold dimmed green'
format = 'via $symbol [${ram} ${ram_pct} | ${swap} ${swap_pct}]($style) '